<?php

namespace AbdallahZaghloul\DesignPatterns\Tests;

use AbdallahZaghloul\DesignPatterns\Structural\Facade\Converter\Photo;
use AbdallahZaghloul\DesignPatterns\Structural\Facade\ConverterFacade;
use PHPUnit\Framework\TestCase;
class FacadeTest extends TestCase
{
    private ConverterFacade $facade;
    private Photo $photo;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->facade = new ConverterFacade();
        $this->photo = new Photo("test","PNG");
    }

    public function testCanConvertPhotoToGif()
    {
        $this->assertEquals("test.GIF animate",$this->facade->convertToGif($this->photo));
    }

    public function testCanConvertPhotoToJPG()
    {
        $this->assertEquals("test.JPG",$this->facade->convertToJPG($this->photo));
    }

    public function testCanCorrectPhotoColor()
    {
        $this->assertEquals("test.PNG color corrected",$this->facade->correctColor($this->photo));
    }
}