<?php

namespace AbdallahZaghloul\DesignPatterns\Structural\Decorator;

class BluePaintDecorator extends PainterDecorator
{
    public const COLOR = 'Blue';

    /**
     * @param Car $car
     * @return Car
     */
    public function paintCar(Car $car): Car
    {
        $car->setColor(self::COLOR);
        return parent::paintCar($car); // TODO: Change the autogenerated stub
    }

}